[program:legal-shop-worker]
command=/usr/bin/php /var/www/legal-shop/bin/worker.php
process_name=%(program_name)s
numprocs=1
autostart=true
autorestart=true
startsecs=1
startretries=3
user=www-data
redirect_stderr=true
stdout_logfile=/var/www/legal-shop/storage/worker-supervisor.log
stopwaitsecs=10
